Update to 1.16.4
DevotedMC/CropControl pull request #9
Opened 2021-04-08 15:07 UTC by Protonull

2021-04-08 18:06 UTC, ProgrammerDan requested changes
Overall great work, lots of cleanup to conform to style guide that I and other original author neglected to do, and some nice updates to more "modern" Java, thank you.

Couple of concerns that I've listed that should motivate a few small changes, but overall great.

I am hopeful that follow-up PRs add any new crops, and hopefully testing shows that the Physics-based-change catch we'd implemented here still works.

2021-04-08 18:06 UTC, ProgrammerDan commented on src/main/java/com/programmerdan/minecraft/cropcontrol/config/ToolConfig.java
> -		if (!ignoreDurability() &&
I presume there is still a way for servers to know what durability a tool has, yes? This durability check was not a type check, but was to allow "bonus" or alteration of drops as a tool gained damage, it'd be nice to retain that feature if possible.

2021-04-08 18:06 UTC, ProgrammerDan commented on src/main/java/com/programmerdan/minecraft/cropcontrol/data/Crop.java
> +					crop.cropType = Material.valueOf(results.getString(6));
Since this load is no longer a naive string pull, probably wise to wrap in a try-catch so a bad entry in the DB doesn't blow up all loading.

2021-04-08 18:06 UTC, ProgrammerDan commented on src/main/java/com/programmerdan/minecraft/cropcontrol/data/Sapling.java
> +					sapling.saplingType = Material.valueOf(results.getString(6));
Same as other comment here; valueOf explodes if the string isn't a match, good idea to wrap this with try/catch so that just this single sapling explodes and not all loading in the chunk.

2021-04-08 18:06 UTC, ProgrammerDan commented on src/main/java/com/programmerdan/minecraft/cropcontrol/data/Tree.java
> +					tree.treeType = TreeType.valueOf(results.getString(6));
trend here; wrap with try/catch in case of bad / outdated DB, only this one tree will fail not preload

2021-04-08 18:06 UTC, ProgrammerDan commented on src/main/java/com/programmerdan/minecraft/cropcontrol/data/Tree.java
> +					tree.treeType = TreeType.valueOf(results.getString(6));
None of upstream try/catch handled the IllegalArgumentException if valueOf fails due to old data in DB or bad data. Good idea to wrap here as well as exception would propagate

2021-04-08 18:06 UTC, ProgrammerDan commented on src/main/java/com/programmerdan/minecraft/cropcontrol/data/TreeComponent.java
> +					component.treeType = TreeType.valueOf(results.getString(7));
Broken record; wrap in try/catch to safely fail this specific treecomponent.

2021-04-08 18:06 UTC, ProgrammerDan commented on src/main/java/com/programmerdan/minecraft/cropcontrol/handler/CropControlEventHandler.java
> +		trackedMaterials.addAll(Tag.LOGS.getValues());
Nice, glad these are available now.

2021-04-08 18:06 UTC, ProgrammerDan commented on src/main/java/com/programmerdan/minecraft/cropcontrol/handler/CropControlEventHandler.java
> +		trackedMaterials.addAll(Tag.LEAVES.getValues());
I think there were some new crops added to Minecraft; will those be addressed in future PRs?

2021-04-08 18:06 UTC, ProgrammerDan commented on src/main/java/com/programmerdan/minecraft/cropcontrol/handler/CropControlEventHandler.java
> +			Crop.create(chunk, x, y, z, blockMaterial, blockMaterial.toString(),
This change seems wrong; why eliminate the use of getBaseCropState() here? Why storing blockMaterial twice?

2021-04-08 18:06 UTC, ProgrammerDan commented on src/main/java/com/programmerdan/minecraft/cropcontrol/handler/CropControlEventHandler.java
> +				} else if (Material.PODZOL == belowM) {
Should be, I think, PODZOL != belowM -- prior check, "is this dirt and not dirt type 2" which should now resolve to "is this not podzol (prior dirt type 2)?"

In fact I think this whole structure is written the way it was due to the Data check req and I wanted the logic separate for clarity. The entire logic reduces to:

```
if (Material.MYCELIUM != belowM && Material.PODZOL != belowM) {
    checkBreak = true;
}
```

as intent of logic just, if we're not on the right kind of soil, check if a physics tick has popped us.

2021-04-08 18:06 UTC, ProgrammerDan commented on src/main/java/com/programmerdan/minecraft/cropcontrol/handler/CropControlEventHandler.java
> +							@Override
good catch

2021-04-08 18:06 UTC, ProgrammerDan commented on src/main/resources/config-enumerated.yml
> -# Slightly self serving, but putting a connection-detail-less version of our initial config into the main repository, both
iirc this file was here specifically to demonstrate all the growth states for all the supported crops. Probably should not have been removed, just cleaned up.

2021-04-08 18:06 UTC, ProgrammerDan commented on src/main/resources/config.yml
> +      # Ignore the durability of the item held.
Again, durability of tool matters; durability of crop doesn't, those changes were fine, but durability of tool matters (or should).

2021-04-08 18:06 UTC, ProgrammerDan commented on src/main/java/com/programmerdan/minecraft/cropcontrol/config/ToolConfig.java
> +	protected ToolConfig(ItemStack template, boolean ignoreAmount,
Returning back to this after getting to the end, yeah, there's no good reason I'm aware of to drop tool durability recognition. This is a feature removed without good reason as far as I can tell.

Intent being, again, "last hit" drop mod, or "new tool" drop modification, etc.

2021-04-08 18:06 UTC, ProgrammerDan commented on src/main/java/com/programmerdan/minecraft/cropcontrol/config/ToolConfig.java
> -		if (!ignoreDurability() &&
In checking, durability has been replaced with ItemMeta, Damageable interface, with getDamage() returning a comparable `int` value. So, durability should be replaced with this ItemMeta Damageable (if available for that ItemStack type).

2021-04-08 18:06 UTC, ProgrammerDan commented on src/main/java/com/programmerdan/minecraft/cropcontrol/config/ToolConfig.java
> +	protected ToolConfig(ItemStack template, boolean ignoreAmount,
(see other comment, but I see it's moved to a Damageable ItemMeta on the ItemStack. Should be converted, not dropped).

2021-04-12 23:59 UTC, Protonull commented
Not sure what to do here :( I made the PR thinking it'd just be the last three commits, not realising that Max's code hadn't already been merged. I know it shows in the commit list but sometimes it can show things that have already been merged. I'm not sure how to proceed now since while this is my PR, all the comments you've made are about Max's code, code which I've never seen before and don't know anything about.

2021-04-13 00:01 UTC, ProgrammerDan commented
Oh, no worries then. I'll look at this more closely as I have time. Thank
you!

On Mon, Apr 12, 2021, 19:59 Alexander ***@***.***> wrote:

> Not sure what to do here :( I made the PR thinking it'd just be the last
> three commits, not realising that Max's code hadn't already been merged. I
> know it shows in the commit list but sometimes it can show things that have
> already been merged. I'm not sure how to proceed now since while this is my
> PR, all the comments you've made are about Max's code, code which I've
> never seen before and don't know anything about.
>
> —
> You are receiving this because you commented.
> Reply to this email directly, view it on GitHub
> <https://github.com/DevotedMC/CropControl/pull/9#issuecomment-818319060>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AADD5DXYFY7BO6HAORL7EATTIOCPHANCNFSM42TCXTMQ>
> .
>

2022-01-17 17:42 UTC, closed without merging